
/**
  ******************************************************************************
  * @file    CAN2020.c
  * @author  SGT Generated by tool
  * @version V0.1.0 (generator)
  * @date    20-December-2022
  * @brief   CAN protocol application/PROFILE layer for use in SGT formula student electric 2016
  ******************************************************************************
  */
#include "stm32f1xx_hal.h"
#include "CAN_IMU_Bridge.h"
#include "main.h"
CAN_TxHeaderTypeDef TxHeader;
CAN_RxHeaderTypeDef RxHeader;
uint8_t TxData[8];
uint8_t RxData[8];
uint32_t TxMailbox;
struct CAN_Msg_Count CAN_msgs_counter;
struct CAN_Msg_Count CAN_msgs_sampler;

void reset_CAN_msgs_counter()
{
	CAN_msgs_sampler.MID_020 = CAN_msgs_counter.MID_020;
	CAN_msgs_counter.MID_020 = 0;

	CAN_msgs_sampler.MID_060 = CAN_msgs_counter.MID_060;
	CAN_msgs_counter.MID_060 = 0;

	CAN_msgs_sampler.MID_070 = CAN_msgs_counter.MID_070;
	CAN_msgs_counter.MID_070 = 0;

	CAN_msgs_sampler.MID_090 = CAN_msgs_counter.MID_090;
	CAN_msgs_counter.MID_090 = 0;

	CAN_msgs_sampler.MID_100 = CAN_msgs_counter.MID_100;
	CAN_msgs_counter.MID_100 = 0;

	CAN_msgs_sampler.MID_120 = CAN_msgs_counter.MID_120;
	CAN_msgs_counter.MID_120 = 0;

	CAN_msgs_sampler.MID_130 = CAN_msgs_counter.MID_130;
	CAN_msgs_counter.MID_130 = 0;

	CAN_msgs_sampler.MID_200 = CAN_msgs_counter.MID_200;
	CAN_msgs_counter.MID_200 = 0;

	CAN_msgs_sampler.MID_220 = CAN_msgs_counter.MID_220;
	CAN_msgs_counter.MID_220 = 0;

	CAN_msgs_sampler.MID_225 = CAN_msgs_counter.MID_225;
	CAN_msgs_counter.MID_225 = 0;

	CAN_msgs_sampler.MID_230 = CAN_msgs_counter.MID_230;
	CAN_msgs_counter.MID_230 = 0;

	CAN_msgs_sampler.MID_250 = CAN_msgs_counter.MID_250;
	CAN_msgs_counter.MID_250 = 0;

	CAN_msgs_sampler.MID_255 = CAN_msgs_counter.MID_255;
	CAN_msgs_counter.MID_255 = 0;

	CAN_msgs_sampler.MID_256 = CAN_msgs_counter.MID_256;
	CAN_msgs_counter.MID_256 = 0;

	CAN_msgs_sampler.MID_257 = CAN_msgs_counter.MID_257;
	CAN_msgs_counter.MID_257 = 0;

	CAN_msgs_sampler.MID_260 = CAN_msgs_counter.MID_260;
	CAN_msgs_counter.MID_260 = 0;

	CAN_msgs_sampler.MID_270 = CAN_msgs_counter.MID_270;
	CAN_msgs_counter.MID_270 = 0;

	CAN_msgs_sampler.MID_280 = CAN_msgs_counter.MID_280;
	CAN_msgs_counter.MID_280 = 0;

	CAN_msgs_sampler.MID_300 = CAN_msgs_counter.MID_300;
	CAN_msgs_counter.MID_300 = 0;

	CAN_msgs_sampler.MID_305 = CAN_msgs_counter.MID_305;
	CAN_msgs_counter.MID_305 = 0;


}


#if defined(Tx_INT_control_data) || defined(Rx_INT_control_data)
    INT_control_data_TypeDef INT_control_data_Data = {
        .car_state = 0,
        .right_w_pump = 0,
        .left_w_pump	 = 0,
        .brake_red = 0,
        .TSAS = 0,
        .killswitch_R = 0,
        .killswitch_L = 0,
        .brake_white = 0,
        .susp_RR = 0,
        .susp_RL = 0,
        .reserved = 0
     };
#endif
    
#ifdef Tx_INT_control_data
void Tx_INT_control_data_Data(CAN_HandleTypeDef* hcan, INT_control_data_TypeDef* INT_control_data_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_INT_control_data;
    TxHeader.DLC = DLC_INT_control_data;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((INT_control_data_Data->car_state)&0b11111111);
    TxData[1] = (uint8_t)((INT_control_data_Data->right_w_pump << 7)&0b11111111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->left_w_pump	 << 6)&0b1111111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->brake_red << 5)&0b111111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->TSAS << 4)&0b11111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->killswitch_R << 3)&0b1111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->killswitch_L << 2)&0b111);
    TxData[1] |= (uint8_t)((INT_control_data_Data->brake_white << 1)&0b11);
    TxData[1] |= (uint8_t)((INT_control_data_Data->susp_RR >> 11)&0b1);
    TxData[2] = (uint8_t)((INT_control_data_Data->susp_RR >> 3)&0b111111111);
    TxData[3] = (uint8_t)((INT_control_data_Data->susp_RR << 5)&0b11111111111111111);
    TxData[3] |= (uint8_t)((INT_control_data_Data->susp_RL >> 7)&0b11111);
    TxData[4] = (uint8_t)((INT_control_data_Data->susp_RL << 1)&0b1111111111111);
    TxData[4] |= (uint8_t)((INT_control_data_Data->reserved >> 7)&0b1);
    TxData[5] = (uint8_t)((INT_control_data_Data->reserved << 1)&0b111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_INT_control_data
void Rx_INT_control_data_Data(CAN_HandleTypeDef* hcan, INT_control_data_TypeDef* INT_control_data_Data)
{
    INT_control_data_Data->car_state = (uint8_t)((RxData[0]&0b11111111));
    INT_control_data_Data->right_w_pump = (uint8_t)(((RxData[1]&0b11111111) >> 7));
    INT_control_data_Data->left_w_pump	 = (uint8_t)(((RxData[1]&0b1111111) >> 6));
    INT_control_data_Data->brake_red = (uint8_t)(((RxData[1]&0b111111) >> 5));
    INT_control_data_Data->TSAS = (uint8_t)(((RxData[1]&0b11111) >> 4));
    INT_control_data_Data->killswitch_R = (uint8_t)(((RxData[1]&0b1111) >> 3));
    INT_control_data_Data->killswitch_L = (uint8_t)(((RxData[1]&0b111) >> 2));
    INT_control_data_Data->brake_white = (uint8_t)(((RxData[1]&0b11) >> 1));
    INT_control_data_Data->susp_RR = (uint16_t)(((RxData[1]&0b1) << 11) | ((RxData[2]&0b111111111) << 3) | ((RxData[3]&0b11111111111111111) >> 5));
    INT_control_data_Data->susp_RL = (uint16_t)(((RxData[3]&0b11111) << 7) | ((RxData[4]&0b1111111111111) >> 1));
    INT_control_data_Data->reserved = (uint8_t)(((RxData[4]&0b1) << 7) | ((RxData[5]&0b111111111) >> 1));

    CAN_msgs_counter.MID_020++;
}
#endif


#if defined(Tx_ACU_control_status) || defined(Rx_ACU_control_status)
    ACU_control_status_TypeDef ACU_control_status_Data = {
        .SHD_IN = 0,
        .SHD_OUT = 0,
        .TSMS = 0,
        .AIR_N = 0,
        .AIR_P = 0,
        .PRECH_60V = 0,
        .IMD_OK = 0,
        .BMS_OK = 0,
        .SIGNAL_ERROR = 0,
        .SHD_RESET = 0,
        .SHD_EN = 0,
        .POLARITY = 0,
        .FANS = 0,
        .IMD_RES = 0,
        .IMD_ERROR = 0
     };
#endif
    
#ifdef Tx_ACU_control_status
void Tx_ACU_control_status_Data(CAN_HandleTypeDef* hcan, ACU_control_status_TypeDef* ACU_control_status_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_ACU_control_status;
    TxHeader.DLC = DLC_ACU_control_status;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((ACU_control_status_Data->SHD_IN << 7)&0b11111111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->SHD_OUT << 6)&0b1111111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->TSMS << 5)&0b111111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->AIR_N << 4)&0b11111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->AIR_P << 3)&0b1111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->PRECH_60V << 2)&0b111);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->IMD_OK << 1)&0b11);
    TxData[0] |= (uint8_t)((ACU_control_status_Data->BMS_OK)&0b1);
    TxData[1] = (uint8_t)((ACU_control_status_Data->SIGNAL_ERROR << 7)&0b11111111);
    TxData[1] |= (uint8_t)((ACU_control_status_Data->SHD_RESET << 6)&0b1111111);
    TxData[1] |= (uint8_t)((ACU_control_status_Data->SHD_EN << 5)&0b111111);
    TxData[1] |= (uint8_t)((ACU_control_status_Data->POLARITY << 4)&0b11111);
    TxData[1] |= (uint8_t)((ACU_control_status_Data->FANS << 3)&0b1111);
    TxData[1] |= (uint8_t)((ACU_control_status_Data->IMD_RES >> 13)&0b111);
    TxData[2] = (uint8_t)((ACU_control_status_Data->IMD_RES >> 5)&0b11111111111);
    TxData[3] = (uint8_t)((ACU_control_status_Data->IMD_RES << 3)&0b1111111111111111111);
    TxData[3] |= (uint8_t)((ACU_control_status_Data->IMD_ERROR)&0b111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_ACU_control_status
void Rx_ACU_control_status_Data(CAN_HandleTypeDef* hcan, ACU_control_status_TypeDef* ACU_control_status_Data)
{
    ACU_control_status_Data->SHD_IN = (uint8_t)(((RxData[0]&0b11111111) >> 7));
    ACU_control_status_Data->SHD_OUT = (uint8_t)(((RxData[0]&0b1111111) >> 6));
    ACU_control_status_Data->TSMS = (uint8_t)(((RxData[0]&0b111111) >> 5));
    ACU_control_status_Data->AIR_N = (uint8_t)(((RxData[0]&0b11111) >> 4));
    ACU_control_status_Data->AIR_P = (uint8_t)(((RxData[0]&0b1111) >> 3));
    ACU_control_status_Data->PRECH_60V = (uint8_t)(((RxData[0]&0b111) >> 2));
    ACU_control_status_Data->IMD_OK = (uint8_t)(((RxData[0]&0b11) >> 1));
    ACU_control_status_Data->BMS_OK = (uint8_t)((RxData[0]&0b1));
    ACU_control_status_Data->SIGNAL_ERROR = (uint8_t)(((RxData[1]&0b11111111) >> 7));
    ACU_control_status_Data->SHD_RESET = (uint8_t)(((RxData[1]&0b1111111) >> 6));
    ACU_control_status_Data->SHD_EN = (uint8_t)(((RxData[1]&0b111111) >> 5));
    ACU_control_status_Data->POLARITY = (uint8_t)(((RxData[1]&0b11111) >> 4));
    ACU_control_status_Data->FANS = (uint8_t)(((RxData[1]&0b1111) >> 3));
    ACU_control_status_Data->IMD_RES = (uint16_t)(((RxData[1]&0b111) << 13) | ((RxData[2]&0b11111111111) << 5) | ((RxData[3]&0b1111111111111111111) >> 3));
    ACU_control_status_Data->IMD_ERROR = (uint8_t)((RxData[3]&0b111));

    CAN_msgs_counter.MID_060++;
}
#endif


#if defined(Tx_ACU_TSBox_data) || defined(Rx_ACU_TSBox_data)
    ACU_TSBox_data_TypeDef ACU_TSBox_data_Data = {
        .power = 0,
        .current = 0,
        .voltage = 0
     };
#endif
    
#ifdef Tx_ACU_TSBox_data
void Tx_ACU_TSBox_data_Data(CAN_HandleTypeDef* hcan, ACU_TSBox_data_TypeDef* ACU_TSBox_data_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_ACU_TSBox_data;
    TxHeader.DLC = DLC_ACU_TSBox_data;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((ACU_TSBox_data_Data->power >> 8)&0b11111111);
    TxData[1] = (uint8_t)((ACU_TSBox_data_Data->power)&0b1111111111111111);
    TxData[2] = (uint8_t)((ACU_TSBox_data_Data->current >> 8)&0b11111111);
    TxData[3] = (uint8_t)((ACU_TSBox_data_Data->current)&0b1111111111111111);
    TxData[4] = (uint8_t)((ACU_TSBox_data_Data->voltage >> 8)&0b11111111);
    TxData[5] = (uint8_t)((ACU_TSBox_data_Data->voltage)&0b1111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_ACU_TSBox_data
void Rx_ACU_TSBox_data_Data(CAN_HandleTypeDef* hcan, ACU_TSBox_data_TypeDef* ACU_TSBox_data_Data)
{
    ACU_TSBox_data_Data->power = (int16_t)(((RxData[0]&0b11111111) << 8) | (RxData[1]&0b1111111111111111));
    ACU_TSBox_data_Data->current = (int16_t)(((RxData[2]&0b11111111) << 8) | (RxData[3]&0b1111111111111111));
    ACU_TSBox_data_Data->voltage = (int16_t)(((RxData[4]&0b11111111) << 8) | (RxData[5]&0b1111111111111111));

    CAN_msgs_counter.MID_070++;
}
#endif


#if defined(Tx_AMS_acuseg_voltage) || defined(Rx_AMS_acuseg_voltage)
    AMS_acuseg_voltage_TypeDef AMS_acuseg_voltage_Data = {
        .volt_ident = 0,
        .voltage1 = 0,
        .voltage2 = 0,
        .voltage3 = 0,
        .voltage4 = 0,
        .voltage5 = 0,
        .voltage6 = 0,
        .voltage7 = 0
     };
#endif
    
#ifdef Tx_AMS_acuseg_voltage
void Tx_AMS_acuseg_voltage_Data(CAN_HandleTypeDef* hcan, AMS_acuseg_voltage_TypeDef* AMS_acuseg_voltage_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_AMS_acuseg_voltage;
    TxHeader.DLC = DLC_AMS_acuseg_voltage;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((AMS_acuseg_voltage_Data->volt_ident)&0b11111111);
    TxData[1] = (uint8_t)((AMS_acuseg_voltage_Data->voltage1)&0b11111111);
    TxData[2] = (uint8_t)((AMS_acuseg_voltage_Data->voltage2)&0b11111111);
    TxData[3] = (uint8_t)((AMS_acuseg_voltage_Data->voltage3)&0b11111111);
    TxData[4] = (uint8_t)((AMS_acuseg_voltage_Data->voltage4)&0b11111111);
    TxData[5] = (uint8_t)((AMS_acuseg_voltage_Data->voltage5)&0b11111111);
    TxData[6] = (uint8_t)((AMS_acuseg_voltage_Data->voltage6)&0b11111111);
    TxData[7] = (uint8_t)((AMS_acuseg_voltage_Data->voltage7)&0b11111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_AMS_acuseg_voltage
void Rx_AMS_acuseg_voltage_Data(CAN_HandleTypeDef* hcan, AMS_acuseg_voltage_TypeDef* AMS_acuseg_voltage_Data)
{
    AMS_acuseg_voltage_Data->volt_ident = (uint8_t)((RxData[0]&0b11111111));
    AMS_acuseg_voltage_Data->voltage1 = (uint8_t)((RxData[1]&0b11111111));
    AMS_acuseg_voltage_Data->voltage2 = (uint8_t)((RxData[2]&0b11111111));
    AMS_acuseg_voltage_Data->voltage3 = (uint8_t)((RxData[3]&0b11111111));
    AMS_acuseg_voltage_Data->voltage4 = (uint8_t)((RxData[4]&0b11111111));
    AMS_acuseg_voltage_Data->voltage5 = (uint8_t)((RxData[5]&0b11111111));
    AMS_acuseg_voltage_Data->voltage6 = (uint8_t)((RxData[6]&0b11111111));
    AMS_acuseg_voltage_Data->voltage7 = (uint8_t)((RxData[7]&0b11111111));

    CAN_msgs_counter.MID_090++;
}
#endif


#if defined(Tx_AMS_acuseg_temp) || defined(Rx_AMS_acuseg_temp)
    AMS_acuseg_temp_TypeDef AMS_acuseg_temp_Data = {
        .temp_ident = 0,
        .temp1 = 0,
        .temp2 = 0,
        .temp3 = 0,
        .temp4 = 0,
        .temp5 = 0,
        .temp6 = 0,
        .temp7 = 0
     };
#endif
    
#ifdef Tx_AMS_acuseg_temp
void Tx_AMS_acuseg_temp_Data(CAN_HandleTypeDef* hcan, AMS_acuseg_temp_TypeDef* AMS_acuseg_temp_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_AMS_acuseg_temp;
    TxHeader.DLC = DLC_AMS_acuseg_temp;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((AMS_acuseg_temp_Data->temp_ident)&0b11111111);
    TxData[1] = (uint8_t)((AMS_acuseg_temp_Data->temp1)&0b11111111);
    TxData[2] = (uint8_t)((AMS_acuseg_temp_Data->temp2)&0b11111111);
    TxData[3] = (uint8_t)((AMS_acuseg_temp_Data->temp3)&0b11111111);
    TxData[4] = (uint8_t)((AMS_acuseg_temp_Data->temp4)&0b11111111);
    TxData[5] = (uint8_t)((AMS_acuseg_temp_Data->temp5)&0b11111111);
    TxData[6] = (uint8_t)((AMS_acuseg_temp_Data->temp6)&0b11111111);
    TxData[7] = (uint8_t)((AMS_acuseg_temp_Data->temp7)&0b11111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_AMS_acuseg_temp
void Rx_AMS_acuseg_temp_Data(CAN_HandleTypeDef* hcan, AMS_acuseg_temp_TypeDef* AMS_acuseg_temp_Data)
{
    AMS_acuseg_temp_Data->temp_ident = (uint8_t)((RxData[0]&0b11111111));
    AMS_acuseg_temp_Data->temp1 = (uint8_t)((RxData[1]&0b11111111));
    AMS_acuseg_temp_Data->temp2 = (uint8_t)((RxData[2]&0b11111111));
    AMS_acuseg_temp_Data->temp3 = (uint8_t)((RxData[3]&0b11111111));
    AMS_acuseg_temp_Data->temp4 = (uint8_t)((RxData[4]&0b11111111));
    AMS_acuseg_temp_Data->temp5 = (uint8_t)((RxData[5]&0b11111111));
    AMS_acuseg_temp_Data->temp6 = (uint8_t)((RxData[6]&0b11111111));
    AMS_acuseg_temp_Data->temp7 = (uint8_t)((RxData[7]&0b11111111));

    CAN_msgs_counter.MID_100++;
}
#endif


#if defined(Tx_FCU_pedal_data) || defined(Rx_FCU_pedal_data)
    FCU_pedal_data_TypeDef FCU_pedal_data_Data = {
        .APPS1 = 0,
        .APPS2 = 0,
        .brake1 = 0,
        .brake2 = 0
     };
#endif
    
#ifdef Tx_FCU_pedal_data
void Tx_FCU_pedal_data_Data(CAN_HandleTypeDef* hcan, FCU_pedal_data_TypeDef* FCU_pedal_data_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_FCU_pedal_data;
    TxHeader.DLC = DLC_FCU_pedal_data;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((FCU_pedal_data_Data->APPS1)&0b11111111);
    TxData[1] = (uint8_t)((FCU_pedal_data_Data->APPS2)&0b11111111);
    TxData[2] = (uint8_t)((FCU_pedal_data_Data->brake1)&0b11111111);
    TxData[3] = (uint8_t)((FCU_pedal_data_Data->brake2)&0b11111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_FCU_pedal_data
void Rx_FCU_pedal_data_Data(CAN_HandleTypeDef* hcan, FCU_pedal_data_TypeDef* FCU_pedal_data_Data)
{
    FCU_pedal_data_Data->APPS1 = (uint8_t)((RxData[0]&0b11111111));
    FCU_pedal_data_Data->APPS2 = (uint8_t)((RxData[1]&0b11111111));
    FCU_pedal_data_Data->brake1 = (uint8_t)((RxData[2]&0b11111111));
    FCU_pedal_data_Data->brake2 = (uint8_t)((RxData[3]&0b11111111));

    CAN_msgs_counter.MID_120++;
}
#endif


#if defined(Tx_FCU_steercont_data) || defined(Rx_FCU_steercont_data)
    FCU_steercont_data_TypeDef FCU_steercont_data_Data = {
        .steer = 0,
        .brake_pos = 0,
        .RTD = 0,
        .BOTS = 0,
        .SHDB = 0,
        .INERTIA_SW = 0
     };
#endif
    
#ifdef Tx_FCU_steercont_data
void Tx_FCU_steercont_data_Data(CAN_HandleTypeDef* hcan, FCU_steercont_data_TypeDef* FCU_steercont_data_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_FCU_steercont_data;
    TxHeader.DLC = DLC_FCU_steercont_data;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((FCU_steercont_data_Data->steer)&0b11111111);
    TxData[1] = (uint8_t)((FCU_steercont_data_Data->brake_pos)&0b11111111);
    TxData[2] = (uint8_t)((FCU_steercont_data_Data->RTD << 7)&0b11111111);
    TxData[2] |= (uint8_t)((FCU_steercont_data_Data->BOTS << 6)&0b1111111);
    TxData[2] |= (uint8_t)((FCU_steercont_data_Data->SHDB << 5)&0b111111);
    TxData[2] |= (uint8_t)((FCU_steercont_data_Data->INERTIA_SW << 4)&0b11111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_FCU_steercont_data
void Rx_FCU_steercont_data_Data(CAN_HandleTypeDef* hcan, FCU_steercont_data_TypeDef* FCU_steercont_data_Data)
{
    FCU_steercont_data_Data->steer = (int8_t)((RxData[0]&0b11111111));
    FCU_steercont_data_Data->brake_pos = (uint8_t)((RxData[1]&0b11111111));
    FCU_steercont_data_Data->RTD = (uint8_t)(((RxData[2]&0b11111111) >> 7));
    FCU_steercont_data_Data->BOTS = (uint8_t)(((RxData[2]&0b1111111) >> 6));
    FCU_steercont_data_Data->SHDB = (uint8_t)(((RxData[2]&0b111111) >> 5));
    FCU_steercont_data_Data->INERTIA_SW = (uint8_t)(((RxData[2]&0b11111) >> 4));

    CAN_msgs_counter.MID_130++;
}
#endif


#if defined(Tx_DSH_shutdown_status) || defined(Rx_DSH_shutdown_status)
    DSH_shutdown_status_TypeDef DSH_shutdown_status_Data = {
        .RTD = 0,
        .SHDB = 0,
        .INERTIA_SW = 0
     };
#endif
    
#ifdef Tx_DSH_shutdown_status
void Tx_DSH_shutdown_status_Data(CAN_HandleTypeDef* hcan, DSH_shutdown_status_TypeDef* DSH_shutdown_status_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_DSH_shutdown_status;
    TxHeader.DLC = DLC_DSH_shutdown_status;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((DSH_shutdown_status_Data->RTD << 7)&0b11111111);
    TxData[0] |= (uint8_t)((DSH_shutdown_status_Data->SHDB << 6)&0b1111111);
    TxData[0] |= (uint8_t)((DSH_shutdown_status_Data->INERTIA_SW << 5)&0b111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_DSH_shutdown_status
void Rx_DSH_shutdown_status_Data(CAN_HandleTypeDef* hcan, DSH_shutdown_status_TypeDef* DSH_shutdown_status_Data)
{
    DSH_shutdown_status_Data->RTD = (uint8_t)(((RxData[0]&0b11111111) >> 7));
    DSH_shutdown_status_Data->SHDB = (uint8_t)(((RxData[0]&0b1111111) >> 6));
    DSH_shutdown_status_Data->INERTIA_SW = (uint8_t)(((RxData[0]&0b111111) >> 5));

    CAN_msgs_counter.MID_200++;
}
#endif


#if defined(Tx_AMS_segment_state) || defined(Rx_AMS_segment_state)
    AMS_segment_state_TypeDef AMS_segment_state_Data = {
        .AMS_Mode = 0,
        .AMS_Faults = 0,
        .CellVolt_L = 0,
        .CellVolt_H = 0,
        .CellTemp_L = 0,
        .CellTemp_H = 0,
        .BMS_Ident = 0
     };
#endif

#if defined(Tx_ACU_AMS_command) || defined(Rx_ACU_AMS_command)
    ACU_AMS_command_TypeDef ACU_AMS_command_Data = {
        .meas_state = 0,
        .flags = 0
     };
#endif
    
#ifdef Tx_ACU_AMS_command
void Tx_ACU_AMS_command_Data(CAN_HandleTypeDef* hcan, ACU_AMS_command_TypeDef* ACU_AMS_command_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_ACU_AMS_command;
    TxHeader.DLC = DLC_ACU_AMS_command;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((ACU_AMS_command_Data->meas_state)&0b11111111);
    TxData[1] = (uint8_t)((ACU_AMS_command_Data->flags >> 8)&0b11111111);
    TxData[2] = (uint8_t)((ACU_AMS_command_Data->flags)&0b1111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_ACU_AMS_command
void Rx_ACU_AMS_command_Data(CAN_HandleTypeDef* hcan, ACU_AMS_command_TypeDef* ACU_AMS_command_Data)
{
    ACU_AMS_command_Data->meas_state = (uint8_t)((RxData[0]&0b11111111));
    ACU_AMS_command_Data->flags = (uint16_t)(((RxData[1]&0b11111111) << 8) | (RxData[2]&0b1111111111111111));

    CAN_msgs_counter.MID_220++;
}
#endif


#if defined(Tx_FCU_sensor_error) || defined(Rx_FCU_sensor_error)
    FCU_sensor_error_TypeDef FCU_sensor_error_Data = {
        .error = 0,
        .dummy = 0
     };
#endif
    
#ifdef Tx_FCU_sensor_error
void Tx_FCU_sensor_error_Data(CAN_HandleTypeDef* hcan, FCU_sensor_error_TypeDef* FCU_sensor_error_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_FCU_sensor_error;
    TxHeader.DLC = DLC_FCU_sensor_error;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((FCU_sensor_error_Data->error)&0b11111111);
    TxData[1] = (uint8_t)((FCU_sensor_error_Data->dummy >> 24)&0b11111111);
    TxData[2] = (uint8_t)((FCU_sensor_error_Data->dummy >> 16)&0b1111111111111111);
    TxData[3] = (uint8_t)((FCU_sensor_error_Data->dummy >> 8)&0b111111111111111111111111);
    TxData[4] = (uint8_t)((FCU_sensor_error_Data->dummy)&0b11111111111111111111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_FCU_sensor_error
void Rx_FCU_sensor_error_Data(CAN_HandleTypeDef* hcan, FCU_sensor_error_TypeDef* FCU_sensor_error_Data)
{
    FCU_sensor_error_Data->error = (uint8_t)((RxData[0]&0b11111111));
    FCU_sensor_error_Data->dummy = (uint32_t)(((RxData[1]&0b11111111) << 24) | ((RxData[2]&0b1111111111111111) << 16) | ((RxData[3]&0b111111111111111111111111) << 8) | (RxData[4]&0b11111111111111111111111111111111));

    CAN_msgs_counter.MID_225++;
}
#endif


#if defined(Tx_DSH_oil_temp) || defined(Rx_DSH_oil_temp)
    DSH_oil_temp_TypeDef DSH_oil_temp_Data = {
        .FL_temp = 0,
        .FR_temp = 0,
        .RL_temp = 0,
        .RR_temp = 0
     };
#endif
    
#ifdef Tx_DSH_oil_temp
void Tx_DSH_oil_temp_Data(CAN_HandleTypeDef* hcan, DSH_oil_temp_TypeDef* DSH_oil_temp_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_DSH_oil_temp;
    TxHeader.DLC = DLC_DSH_oil_temp;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((DSH_oil_temp_Data->FL_temp >> 8)&0b11111111);
    TxData[1] = (uint8_t)((DSH_oil_temp_Data->FL_temp)&0b1111111111111111);
    TxData[2] = (uint8_t)((DSH_oil_temp_Data->FR_temp >> 8)&0b11111111);
    TxData[3] = (uint8_t)((DSH_oil_temp_Data->FR_temp)&0b1111111111111111);
    TxData[4] = (uint8_t)((DSH_oil_temp_Data->RL_temp >> 8)&0b11111111);
    TxData[5] = (uint8_t)((DSH_oil_temp_Data->RL_temp)&0b1111111111111111);
    TxData[6] = (uint8_t)((DSH_oil_temp_Data->RR_temp >> 8)&0b11111111);
    TxData[7] = (uint8_t)((DSH_oil_temp_Data->RR_temp)&0b1111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_DSH_oil_temp
void Rx_DSH_oil_temp_Data(CAN_HandleTypeDef* hcan, DSH_oil_temp_TypeDef* DSH_oil_temp_Data)
{
    DSH_oil_temp_Data->FL_temp = (uint16_t)(((RxData[0]&0b11111111) << 8) | (RxData[1]&0b1111111111111111));
    DSH_oil_temp_Data->FR_temp = (uint16_t)(((RxData[2]&0b11111111) << 8) | (RxData[3]&0b1111111111111111));
    DSH_oil_temp_Data->RL_temp = (uint16_t)(((RxData[4]&0b11111111) << 8) | (RxData[5]&0b1111111111111111));
    DSH_oil_temp_Data->RR_temp = (uint16_t)(((RxData[6]&0b11111111) << 8) | (RxData[7]&0b1111111111111111));

    CAN_msgs_counter.MID_230++;
}
#endif


#if defined(Tx_DSH_suspension_sensors_raw) || defined(Rx_DSH_suspension_sensors_raw)
    DSH_suspension_sensors_raw_TypeDef DSH_suspension_sensors_raw_Data = {
        .FA = 0,
        .FB = 0,
        .RA = 0,
        .RB = 0
     };
#endif
    
#ifdef Tx_DSH_suspension_sensors_raw
void Tx_DSH_suspension_sensors_raw_Data(CAN_HandleTypeDef* hcan, DSH_suspension_sensors_raw_TypeDef* DSH_suspension_sensors_raw_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_DSH_suspension_sensors_raw;
    TxHeader.DLC = DLC_DSH_suspension_sensors_raw;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((DSH_suspension_sensors_raw_Data->FA >> 8)&0b11111111);
    TxData[1] = (uint8_t)((DSH_suspension_sensors_raw_Data->FA)&0b1111111111111111);
    TxData[2] = (uint8_t)((DSH_suspension_sensors_raw_Data->FB >> 8)&0b11111111);
    TxData[3] = (uint8_t)((DSH_suspension_sensors_raw_Data->FB)&0b1111111111111111);
    TxData[4] = (uint8_t)((DSH_suspension_sensors_raw_Data->RA >> 8)&0b11111111);
    TxData[5] = (uint8_t)((DSH_suspension_sensors_raw_Data->RA)&0b1111111111111111);
    TxData[6] = (uint8_t)((DSH_suspension_sensors_raw_Data->RB >> 8)&0b11111111);
    TxData[7] = (uint8_t)((DSH_suspension_sensors_raw_Data->RB)&0b1111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_DSH_suspension_sensors_raw
void Rx_DSH_suspension_sensors_raw_Data(CAN_HandleTypeDef* hcan, DSH_suspension_sensors_raw_TypeDef* DSH_suspension_sensors_raw_Data)
{
    DSH_suspension_sensors_raw_Data->FA = (uint16_t)(((RxData[0]&0b11111111) << 8) | (RxData[1]&0b1111111111111111));
    DSH_suspension_sensors_raw_Data->FB = (uint16_t)(((RxData[2]&0b11111111) << 8) | (RxData[3]&0b1111111111111111));
    DSH_suspension_sensors_raw_Data->RA = (uint16_t)(((RxData[4]&0b11111111) << 8) | (RxData[5]&0b1111111111111111));
    DSH_suspension_sensors_raw_Data->RB = (uint16_t)(((RxData[6]&0b11111111) << 8) | (RxData[7]&0b1111111111111111));

    CAN_msgs_counter.MID_250++;
}
#endif


#if defined(Tx_INT_coolant_temp) || defined(Rx_INT_coolant_temp)
    INT_coolant_temp_TypeDef INT_coolant_temp_Data = {
        .Temp_L1 = 0,
        .Temp_L2 = 0,
        .Temp_L3 = 0,
        .Temp_L4 = 0,
        .Temp_R1 = 0,
        .Temp_R2 = 0,
        .Temp_R3 = 0,
        .Temp_R4 = 0
     };
#endif
    
#ifdef Tx_INT_coolant_temp
void Tx_INT_coolant_temp_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_TypeDef* INT_coolant_temp_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_INT_coolant_temp;
    TxHeader.DLC = DLC_INT_coolant_temp;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((INT_coolant_temp_Data->Temp_L1)&0b11111111);
    TxData[1] = (uint8_t)((INT_coolant_temp_Data->Temp_L2)&0b11111111);
    TxData[2] = (uint8_t)((INT_coolant_temp_Data->Temp_L3)&0b11111111);
    TxData[3] = (uint8_t)((INT_coolant_temp_Data->Temp_L4)&0b11111111);
    TxData[4] = (uint8_t)((INT_coolant_temp_Data->Temp_R1)&0b11111111);
    TxData[5] = (uint8_t)((INT_coolant_temp_Data->Temp_R2)&0b11111111);
    TxData[6] = (uint8_t)((INT_coolant_temp_Data->Temp_R3)&0b11111111);
    TxData[7] = (uint8_t)((INT_coolant_temp_Data->Temp_R4)&0b11111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_INT_coolant_temp
void Rx_INT_coolant_temp_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_TypeDef* INT_coolant_temp_Data)
{
    INT_coolant_temp_Data->Temp_L1 = (uint8_t)((RxData[0]&0b11111111));
    INT_coolant_temp_Data->Temp_L2 = (uint8_t)((RxData[1]&0b11111111));
    INT_coolant_temp_Data->Temp_L3 = (uint8_t)((RxData[2]&0b11111111));
    INT_coolant_temp_Data->Temp_L4 = (uint8_t)((RxData[3]&0b11111111));
    INT_coolant_temp_Data->Temp_R1 = (uint8_t)((RxData[4]&0b11111111));
    INT_coolant_temp_Data->Temp_R2 = (uint8_t)((RxData[5]&0b11111111));
    INT_coolant_temp_Data->Temp_R3 = (uint8_t)((RxData[6]&0b11111111));
    INT_coolant_temp_Data->Temp_R4 = (uint8_t)((RxData[7]&0b11111111));

    CAN_msgs_counter.MID_255++;
}
#endif


#if defined(Tx_INT_coolant_temp_left_raw) || defined(Rx_INT_coolant_temp_left_raw)
    INT_coolant_temp_left_raw_TypeDef INT_coolant_temp_left_raw_Data = {
        .Temp_L1_raw = 0,
        .Temp_L2_raw = 0,
        .Temp_L3_raw = 0,
        .Temp_L4_raw = 0
     };
#endif
    
#ifdef Tx_INT_coolant_temp_left_raw
void Tx_INT_coolant_temp_left_raw_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_left_raw_TypeDef* INT_coolant_temp_left_raw_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_INT_coolant_temp_left_raw;
    TxHeader.DLC = DLC_INT_coolant_temp_left_raw;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L1_raw >> 4)&0b11111111);
    TxData[1] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L1_raw << 4)&0b1111111111111111);
    TxData[1] |= (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L2_raw >> 8)&0b1111);
    TxData[2] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L2_raw)&0b111111111111);
    TxData[3] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L3_raw >> 4)&0b11111111);
    TxData[4] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L3_raw << 4)&0b1111111111111111);
    TxData[4] |= (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L4_raw >> 8)&0b1111);
    TxData[5] = (uint8_t)((INT_coolant_temp_left_raw_Data->Temp_L4_raw)&0b111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_INT_coolant_temp_left_raw
void Rx_INT_coolant_temp_left_raw_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_left_raw_TypeDef* INT_coolant_temp_left_raw_Data)
{
    INT_coolant_temp_left_raw_Data->Temp_L1_raw = (uint16_t)(((RxData[0]&0b11111111) << 4) | ((RxData[1]&0b1111111111111111) >> 4));
    INT_coolant_temp_left_raw_Data->Temp_L2_raw = (uint16_t)(((RxData[1]&0b1111) << 8) | (RxData[2]&0b111111111111));
    INT_coolant_temp_left_raw_Data->Temp_L3_raw = (uint16_t)(((RxData[3]&0b11111111) << 4) | ((RxData[4]&0b1111111111111111) >> 4));
    INT_coolant_temp_left_raw_Data->Temp_L4_raw = (uint16_t)(((RxData[4]&0b1111) << 8) | (RxData[5]&0b111111111111));

    CAN_msgs_counter.MID_256++;
}
#endif


#if defined(Tx_INT_coolant_temp_right_raw) || defined(Rx_INT_coolant_temp_right_raw)
    INT_coolant_temp_right_raw_TypeDef INT_coolant_temp_right_raw_Data = {
        .Temp_R1_raw = 0,
        .Temp_R2_raw = 0,
        .Temp_R3_raw = 0,
        .Temp_R4_raw = 0
     };
#endif
    
#ifdef Tx_INT_coolant_temp_right_raw
void Tx_INT_coolant_temp_right_raw_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_right_raw_TypeDef* INT_coolant_temp_right_raw_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_INT_coolant_temp_right_raw;
    TxHeader.DLC = DLC_INT_coolant_temp_right_raw;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R1_raw >> 4)&0b11111111);
    TxData[1] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R1_raw << 4)&0b1111111111111111);
    TxData[1] |= (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R2_raw >> 8)&0b1111);
    TxData[2] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R2_raw)&0b111111111111);
    TxData[3] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R3_raw >> 4)&0b11111111);
    TxData[4] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R3_raw << 4)&0b1111111111111111);
    TxData[4] |= (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R4_raw >> 8)&0b1111);
    TxData[5] = (uint8_t)((INT_coolant_temp_right_raw_Data->Temp_R4_raw)&0b111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);
}
#endif
#ifdef Rx_INT_coolant_temp_right_raw
void Rx_INT_coolant_temp_right_raw_Data(CAN_HandleTypeDef* hcan, INT_coolant_temp_right_raw_TypeDef* INT_coolant_temp_right_raw_Data)
{
    INT_coolant_temp_right_raw_Data->Temp_R1_raw = (uint16_t)(((RxData[0]&0b11111111) << 4) | ((RxData[1]&0b1111111111111111) >> 4));
    INT_coolant_temp_right_raw_Data->Temp_R2_raw = (uint16_t)(((RxData[1]&0b1111) << 8) | (RxData[2]&0b111111111111));
    INT_coolant_temp_right_raw_Data->Temp_R3_raw = (uint16_t)(((RxData[3]&0b11111111) << 4) | ((RxData[4]&0b1111111111111111) >> 4));
    INT_coolant_temp_right_raw_Data->Temp_R4_raw = (uint16_t)(((RxData[4]&0b1111) << 8) | (RxData[5]&0b111111111111));

    CAN_msgs_counter.MID_257++;
}
#endif


#if defined(Tx_MCU_IMU_angular_velocity) || defined(Rx_MCU_IMU_angular_velocity)
    MCU_IMU_angular_velocity_TypeDef MCU_IMU_angular_velocity_Data = {
        .gyrX = 0,
        .gyrY = 0,
        .gyrZ = 0
     };
#endif
    
#ifdef Tx_MCU_IMU_angular_velocity
void Tx_MCU_IMU_angular_velocity_Data(CAN_HandleTypeDef* hcan, MCU_IMU_angular_velocity_TypeDef* MCU_IMU_angular_velocity_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_MCU_IMU_angular_velocity;
    TxHeader.DLC = DLC_MCU_IMU_angular_velocity;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrX >> 12)&0b11111111);
    TxData[1] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrX >> 4)&0b1111111111111111);
    TxData[2] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrX << 4)&0b111111111111111111111111);
    TxData[2] |= (uint8_t)((MCU_IMU_angular_velocity_Data->gyrY >> 16)&0b1111);
    TxData[3] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrY >> 8)&0b111111111111);
    TxData[4] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrY)&0b11111111111111111111);
    TxData[5] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrZ >> 12)&0b11111111);
    TxData[6] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrZ >> 4)&0b1111111111111111);
    TxData[7] = (uint8_t)((MCU_IMU_angular_velocity_Data->gyrZ << 4)&0b111111111111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

   CAN_msgs_counter.MID_260++;
}
#endif
#ifdef Rx_MCU_IMU_angular_velocity
void Rx_MCU_IMU_angular_velocity_Data(CAN_HandleTypeDef* hcan, MCU_IMU_angular_velocity_TypeDef* MCU_IMU_angular_velocity_Data)
{
    MCU_IMU_angular_velocity_Data->gyrX = (int32_t)(((RxData[0]&0b11111111) << 12) | ((RxData[1]&0b1111111111111111) << 4) | ((RxData[2]&0b111111111111111111111111) >> 4));
    MCU_IMU_angular_velocity_Data->gyrY = (int32_t)(((RxData[2]&0b1111) << 16) | ((RxData[3]&0b111111111111) << 8) | (RxData[4]&0b11111111111111111111));
    MCU_IMU_angular_velocity_Data->gyrZ = (int32_t)(((RxData[5]&0b11111111) << 12) | ((RxData[6]&0b1111111111111111) << 4) | ((RxData[7]&0b111111111111111111111111) >> 4));
}
#endif


#if defined(Tx_MCU_IMU_acceleration) || defined(Rx_MCU_IMU_acceleration)
    MCU_IMU_acceleration_TypeDef MCU_IMU_acceleration_Data = {
        .accX = 0,
        .accY = 0,
        .accZ = 0
     };
#endif
    
#ifdef Tx_MCU_IMU_acceleration
void Tx_MCU_IMU_acceleration_Data(CAN_HandleTypeDef* hcan, MCU_IMU_acceleration_TypeDef* MCU_IMU_acceleration_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_MCU_IMU_acceleration;
    TxHeader.DLC = DLC_MCU_IMU_acceleration;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((MCU_IMU_acceleration_Data->accX >> 12)&0b11111111);
    TxData[1] = (uint8_t)((MCU_IMU_acceleration_Data->accX >> 4)&0b1111111111111111);
    TxData[2] = (uint8_t)((MCU_IMU_acceleration_Data->accX << 4)&0b111111111111111111111111);
    TxData[2] |= (uint8_t)((MCU_IMU_acceleration_Data->accY >> 16)&0b1111);
    TxData[3] = (uint8_t)((MCU_IMU_acceleration_Data->accY >> 8)&0b111111111111);
    TxData[4] = (uint8_t)((MCU_IMU_acceleration_Data->accY)&0b11111111111111111111);
    TxData[5] = (uint8_t)((MCU_IMU_acceleration_Data->accZ >> 12)&0b11111111);
    TxData[6] = (uint8_t)((MCU_IMU_acceleration_Data->accZ >> 4)&0b1111111111111111);
    TxData[7] = (uint8_t)((MCU_IMU_acceleration_Data->accZ << 4)&0b111111111111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

   CAN_msgs_counter.MID_270++;
}
#endif
#ifdef Rx_MCU_IMU_acceleration
void Rx_MCU_IMU_acceleration_Data(CAN_HandleTypeDef* hcan, MCU_IMU_acceleration_TypeDef* MCU_IMU_acceleration_Data)
{
    MCU_IMU_acceleration_Data->accX = (int32_t)(((RxData[0]&0b11111111) << 12) | ((RxData[1]&0b1111111111111111) << 4) | ((RxData[2]&0b111111111111111111111111) >> 4));
    MCU_IMU_acceleration_Data->accY = (int32_t)(((RxData[2]&0b1111) << 16) | ((RxData[3]&0b111111111111) << 8) | (RxData[4]&0b11111111111111111111));
    MCU_IMU_acceleration_Data->accZ = (int32_t)(((RxData[5]&0b11111111) << 12) | ((RxData[6]&0b1111111111111111) << 4) | ((RxData[7]&0b111111111111111111111111) >> 4));
}
#endif


#if defined(Tx_MCU_IMU_euler_angles) || defined(Rx_MCU_IMU_euler_angles)
    MCU_IMU_euler_angles_TypeDef MCU_IMU_euler_angles_Data = {
        .roll = 0,
        .pitch = 0,
        .yaw = 0
     };
#endif
    
#ifdef Tx_MCU_IMU_euler_angles
void Tx_MCU_IMU_euler_angles_Data(CAN_HandleTypeDef* hcan, MCU_IMU_euler_angles_TypeDef* MCU_IMU_euler_angles_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_MCU_IMU_euler_angles;
    TxHeader.DLC = DLC_MCU_IMU_euler_angles;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((MCU_IMU_euler_angles_Data->roll >> 12)&0b11111111);
    TxData[1] = (uint8_t)((MCU_IMU_euler_angles_Data->roll >> 4)&0b1111111111111111);
    TxData[2] = (uint8_t)((MCU_IMU_euler_angles_Data->roll << 4)&0b111111111111111111111111);
    TxData[2] |= (uint8_t)((MCU_IMU_euler_angles_Data->pitch >> 16)&0b1111);
    TxData[3] = (uint8_t)((MCU_IMU_euler_angles_Data->pitch >> 8)&0b111111111111);
    TxData[4] = (uint8_t)((MCU_IMU_euler_angles_Data->pitch)&0b11111111111111111111);
    TxData[5] = (uint8_t)((MCU_IMU_euler_angles_Data->yaw >> 12)&0b11111111);
    TxData[6] = (uint8_t)((MCU_IMU_euler_angles_Data->yaw >> 4)&0b1111111111111111);
    TxData[7] = (uint8_t)((MCU_IMU_euler_angles_Data->yaw << 4)&0b111111111111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

   CAN_msgs_counter.MID_280++;
}
#endif
#ifdef Rx_MCU_IMU_euler_angles
void Rx_MCU_IMU_euler_angles_Data(CAN_HandleTypeDef* hcan, MCU_IMU_euler_angles_TypeDef* MCU_IMU_euler_angles_Data)
{
    MCU_IMU_euler_angles_Data->roll = (int32_t)(((RxData[0]&0b11111111) << 12) | ((RxData[1]&0b1111111111111111) << 4) | ((RxData[2]&0b111111111111111111111111) >> 4));
    MCU_IMU_euler_angles_Data->pitch = (int32_t)(((RxData[2]&0b1111) << 16) | ((RxData[3]&0b111111111111) << 8) | (RxData[4]&0b11111111111111111111));
    MCU_IMU_euler_angles_Data->yaw = (int32_t)(((RxData[5]&0b11111111) << 12) | ((RxData[6]&0b1111111111111111) << 4) | ((RxData[7]&0b111111111111111111111111) >> 4));
}
#endif


#if defined(Tx_MCU_IMU_gps_position) || defined(Rx_MCU_IMU_gps_position)
    MCU_IMU_gps_position_TypeDef MCU_IMU_gps_position_Data = {
        .lat = 0,
        .longitude = 0
     };
#endif
    
#ifdef Tx_MCU_IMU_gps_position
void Tx_MCU_IMU_gps_position_Data(CAN_HandleTypeDef* hcan, MCU_IMU_gps_position_TypeDef* MCU_IMU_gps_position_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_MCU_IMU_gps_position;
    TxHeader.DLC = DLC_MCU_IMU_gps_position;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((MCU_IMU_gps_position_Data->lat >> 24)&0b11111111);
    TxData[1] = (uint8_t)((MCU_IMU_gps_position_Data->lat >> 16)&0b1111111111111111);
    TxData[2] = (uint8_t)((MCU_IMU_gps_position_Data->lat >> 8)&0b111111111111111111111111);
    TxData[3] = (uint8_t)((MCU_IMU_gps_position_Data->lat)&0b11111111111111111111111111111111);
    TxData[4] = (uint8_t)((MCU_IMU_gps_position_Data->longitude >> 24)&0b11111111);
    TxData[5] = (uint8_t)((MCU_IMU_gps_position_Data->longitude >> 16)&0b1111111111111111);
    TxData[6] = (uint8_t)((MCU_IMU_gps_position_Data->longitude >> 8)&0b111111111111111111111111);
    TxData[7] = (uint8_t)((MCU_IMU_gps_position_Data->longitude)&0b11111111111111111111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

   CAN_msgs_counter.MID_300++;
}
#endif
#ifdef Rx_MCU_IMU_gps_position
void Rx_MCU_IMU_gps_position_Data(CAN_HandleTypeDef* hcan, MCU_IMU_gps_position_TypeDef* MCU_IMU_gps_position_Data)
{
    MCU_IMU_gps_position_Data->lat = (uint32_t)(((RxData[0]&0b11111111) << 24) | ((RxData[1]&0b1111111111111111) << 16) | ((RxData[2]&0b111111111111111111111111) << 8) | (RxData[3]&0b11111111111111111111111111111111));
    MCU_IMU_gps_position_Data->longitude = (uint32_t)(((RxData[4]&0b11111111) << 24) | ((RxData[5]&0b1111111111111111) << 16) | ((RxData[6]&0b111111111111111111111111) << 8) | (RxData[7]&0b11111111111111111111111111111111));
}
#endif


#if defined(Tx_MCU_IMU_gps_speed) || defined(Rx_MCU_IMU_gps_speed)
    MCU_IMU_gps_speed_TypeDef MCU_IMU_gps_speed_Data = {
        .gps_velocity = 0
     };
#endif
    
#ifdef Tx_MCU_IMU_gps_speed
void Tx_MCU_IMU_gps_speed_Data(CAN_HandleTypeDef* hcan, MCU_IMU_gps_speed_TypeDef* MCU_IMU_gps_speed_Data)
{
    //hcan->pTxMsg = &CanTxMsg; historic
    TxHeader.StdId = ID_MCU_IMU_gps_speed;
    TxHeader.DLC = DLC_MCU_IMU_gps_speed;
    TxHeader.ExtId = 0x0;
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.IDE = CAN_ID_STD;
        
    TxData[0] = (uint8_t)((MCU_IMU_gps_speed_Data->gps_velocity >> 8)&0b11111111);
    TxData[1] = (uint8_t)((MCU_IMU_gps_speed_Data->gps_velocity)&0b1111111111111111);
                        
   HAL_CAN_ActivateNotification(hcan,0xff);
   HAL_CAN_AddTxMessage(hcan, &TxHeader, TxData, &TxMailbox);
   HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

   CAN_msgs_counter.MID_305++;
}
#endif
#ifdef Rx_MCU_IMU_gps_speed
void Rx_MCU_IMU_gps_speed_Data(CAN_HandleTypeDef* hcan, MCU_IMU_gps_speed_TypeDef* MCU_IMU_gps_speed_Data)
{
    MCU_IMU_gps_speed_Data->gps_velocity = (uint16_t)(((RxData[0]&0b11111111) << 8) | (RxData[1]&0b1111111111111111));
}
#endif


/** \brief Zmaze CAN error ak je
 *
 * \param hcan CAN_HandleTypeDef*
 * \return void
 *
 */
void HAL_CAN_ErrorCallback(CAN_HandleTypeDef *hcan)
{
    hcan->ErrorCode = HAL_CAN_ERROR_NONE;
    hcan->Instance->MSR &= 0x1C;
}
/**
* @brief Event for CAN Rx message
* @param Can controller message structure
*/
void HAL_CAN_RxCpltCallback(CAN_HandleTypeDef* hcan)
{
    switch (RxHeader.StdId)
    {

#ifdef Rx_INT_control_data
        case ID_INT_control_data:
            Rx_INT_control_data_Data(hcan, &INT_control_data_Data);
            break;
#endif

#ifdef Rx_ACU_control_status
        case ID_ACU_control_status:
            Rx_ACU_control_status_Data(hcan, &ACU_control_status_Data);
            break;
#endif

#ifdef Rx_ACU_TSBox_data
        case ID_ACU_TSBox_data:
            Rx_ACU_TSBox_data_Data(hcan, &ACU_TSBox_data_Data);
            break;
#endif

#ifdef Rx_AMS_acuseg_voltage
        case ID_AMS_acuseg_voltage:
            Rx_AMS_acuseg_voltage_Data(hcan, &AMS_acuseg_voltage_Data);
            break;
#endif

#ifdef Rx_AMS_acuseg_temp
        case ID_AMS_acuseg_temp:
            Rx_AMS_acuseg_temp_Data(hcan, &AMS_acuseg_temp_Data);
            break;
#endif

#ifdef Rx_FCU_pedal_data
        case ID_FCU_pedal_data:
            Rx_FCU_pedal_data_Data(hcan, &FCU_pedal_data_Data);
            break;
#endif

#ifdef Rx_FCU_steercont_data
        case ID_FCU_steercont_data:
            Rx_FCU_steercont_data_Data(hcan, &FCU_steercont_data_Data);
            break;
#endif

#ifdef Rx_AMK_setpoints_FL
        case ID_AMK_setpoints_FL:
            Rx_AMK_setpoints_FL_Data(hcan, &AMK_setpoints_FL_Data);
            break;
#endif

#ifdef Rx_AMK_setpoints_FR
        case ID_AMK_setpoints_FR:
            Rx_AMK_setpoints_FR_Data(hcan, &AMK_setpoints_FR_Data);
            break;
#endif

#ifdef Rx_AMK_setpoints_RL
        case ID_AMK_setpoints_RL:
            Rx_AMK_setpoints_RL_Data(hcan, &AMK_setpoints_RL_Data);
            break;
#endif

#ifdef Rx_AMK_setpoints_RR
        case ID_AMK_setpoints_RR:
            Rx_AMK_setpoints_RR_Data(hcan, &AMK_setpoints_RR_Data);
            break;
#endif

#ifdef Rx_DSH_shutdown_status
        case ID_DSH_shutdown_status:
            Rx_DSH_shutdown_status_Data(hcan, &DSH_shutdown_status_Data);
            break;
#endif

#ifdef Rx_AMS_segment_state
        case ID_AMS_segment_state:
            Rx_AMS_segment_state_Data(hcan, &AMS_segment_state_Data);
            break;
#endif

#ifdef Rx_ACU_AMS_command
        case ID_ACU_AMS_command:
            Rx_ACU_AMS_command_Data(hcan, &ACU_AMS_command_Data);
            break;
#endif

#ifdef Rx_FCU_sensor_error
        case ID_FCU_sensor_error:
            Rx_FCU_sensor_error_Data(hcan, &FCU_sensor_error_Data);
            break;
#endif

#ifdef Rx_DSH_oil_temp
        case ID_DSH_oil_temp:
            Rx_DSH_oil_temp_Data(hcan, &DSH_oil_temp_Data);
            break;
#endif

#ifdef Rx_DSH_suspension_sensors_raw
        case ID_DSH_suspension_sensors_raw:
            Rx_DSH_suspension_sensors_raw_Data(hcan, &DSH_suspension_sensors_raw_Data);
            break;
#endif

#ifdef Rx_INT_coolant_temp
        case ID_INT_coolant_temp:
            Rx_INT_coolant_temp_Data(hcan, &INT_coolant_temp_Data);
            break;
#endif

#ifdef Rx_INT_coolant_temp_left_raw
        case ID_INT_coolant_temp_left_raw:
            Rx_INT_coolant_temp_left_raw_Data(hcan, &INT_coolant_temp_left_raw_Data);
            break;
#endif

#ifdef Rx_INT_coolant_temp_right_raw
        case ID_INT_coolant_temp_right_raw:
            Rx_INT_coolant_temp_right_raw_Data(hcan, &INT_coolant_temp_right_raw_Data);
            break;
#endif

#ifdef Rx_MCU_IMU_angular_velocity
        case ID_MCU_IMU_angular_velocity:
            Rx_MCU_IMU_angular_velocity_Data(hcan, &MCU_IMU_angular_velocity_Data);
            break;
#endif

#ifdef Rx_MCU_IMU_acceleration
        case ID_MCU_IMU_acceleration:
            Rx_MCU_IMU_acceleration_Data(hcan, &MCU_IMU_acceleration_Data);
            break;
#endif

#ifdef Rx_MCU_IMU_euler_angles
        case ID_MCU_IMU_euler_angles:
            Rx_MCU_IMU_euler_angles_Data(hcan, &MCU_IMU_euler_angles_Data);
            break;
#endif

#ifdef Rx_MCU_IMU_gps_position
        case ID_MCU_IMU_gps_position:
            Rx_MCU_IMU_gps_position_Data(hcan, &MCU_IMU_gps_position_Data);
            break;
#endif

#ifdef Rx_MCU_IMU_gps_speed
        case ID_MCU_IMU_gps_speed:
            Rx_MCU_IMU_gps_speed_Data(hcan, &MCU_IMU_gps_speed_Data);
            break;
#endif

        default:
            break;
    }
  HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData);

  static uint8_t blink;

    if(!(blink%10))
    {
  		HAL_GPIO_TogglePin(CAN_RX_L_GPIO_Port, CAN_RX_L_Pin);
    }

    blink++;

}

void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef* hcan)
{
	HAL_CAN_RxCpltCallback(hcan);

}

